name: Release

on:
  push:
    branches: [ feature/improvements ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v3
      with:
        node-version: 16

    - name: Install dependencies
      run: yarn install

    - name: Build binaries
      run: yarn build

    - name: Release
      uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: "latest"
        prerelease: false
        draft: false
        files: |
          LICENSE
          dist/*-linux
          dist/*-macos

